import '../about.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons';

export default function aboutMe() {
 return (
  <div>
    <div className='pageTitleContainer'>
      <h3 className="pageTitle">About Me</h3>
    </div>
    <div>
        <p className='faIcon'><FontAwesomeIcon icon={faUser} /></p>
    </div>
    <div>
      <p className="aboutMeText">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Nulla facilisi. Ut at tortor quam. Phasellus eleifend tellus vel justo gravida, in aliquet nulla auctor. Integer tristique urna id velit aliquet, at aliquam eros volutpat. Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non augue sit amet dolor gravida sollicitudin.</p>
      <p className="aboutMeText">Ut at tortor quam. Phasellus eleifend tellus vel justo gravida, in aliquet nulla auctor. Integer tristique urna id velit aliquet, at aliquam eros volutpat. Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod.Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non augue sit a.Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non augue sit a</p>
      <p className="aboutMeText">Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fam. Ut at tortor quam. Phasellus eleifend tellus vel justo gravida, in aliquet nulla auctor. Integer tristique urna id velit aliquet, at aliquam eros volutpat. Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod.Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non augue sit a.Mauris nec semper nibh. Suspendisse potenti. Curabitur accumsan, nisl quis condimentum bibendum, quam lorem pulvinar ligula, at interdum nulla felis sed massa. Vivamus maximus mi et enim facilisis, vel tristique ligula euismod. Proin sodales auctor dui, sed vulputate arcu pulvinar id. In nec est a ligula gravida mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non augue sit a</p>
    </div>
  </div>
 )
}